services:
  people_api:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - serviceName: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - my_network
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network
    command: ["redis-server", "--appendonly", "yes"]


networks:
  my_network:
