services:
  people_api:
    container_name: people_api
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .:/app
      - /app/.venv/ # don't mount .venv
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=test-db
    networks:
      - my_network

  test-db:
    container_name: test-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stats
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - my_network

  dumped-db:
    container_name: dumped-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mensa
    ports:
      - "5432:5432"
    volumes:
      - ./tests/dumps/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - my_network
    profiles:
      - dumpdb

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network
    command: ["redis-server", "--appendonly", "yes"]

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - test-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    networks:
      - my_network

volumes:
  jaeger_data:
  pgadmin_data:

networks:
  my_network:
