version: '3.8'
services:
  people_api:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .:/app
      - /app/.venv/ # don't mount .venv
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=test-db
    networks:
      - my_network

  test-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stats
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - my_network

  dumped-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mensa
    ports:
      - "5432:5432"
    volumes:
      - ./tests/dumps/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - my_network
    profiles:
      - dumpdb

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - test-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    networks:
      - my_network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network
    command: ["redis-server", "--appendonly", "yes"]

  jaeger:
    image: jaegertracing/all-in-one:1.41
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://jaeger-db:9200
    depends_on:
      - jaeger-db
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
      - "4317:4317"
    networks:
      - my_network

  jaeger-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - my_network

volumes:
  pgadmin_data:

networks:
  my_network:
