services:
  people_api:
    container_name: people_api
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - redis
      - jaeger
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - my_network

  sqs_handler:
    container_name: sqs_handler
    build:
      context: .
    command: uv run -m people_api sqs_handler
    depends_on:
      - people_api
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - my_network

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network
    command: ["redis-server", "--appendonly", "yes"]

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0@sha256:2f602552550869fb29b6fd5848c5118d3ef3a2e1d5d45802e3ab9088cb2de8e2
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - action.destructive_requires_name=false
      - xpack.monitoring.collection.enabled=false
      - ES_LOG_LEVEL=trace
      - logger.org.elasticsearch.index.search.slowlog=TRACE
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 30
    networks:
      - my_network
    volumes:
      - jaeger_data:/usr/share/elasticsearch/data

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - COLLECTOR_OTLP_ENABLED=true
      - ES_TAGS_AS_FIELDS_ALL=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
    networks:
      - my_network
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  jaeger_data:

networks:
  my_network:
