services:
  people_api:
    container_name: people_api
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .:/app
      - /app/.venv/ # don't mount .venv
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=test-db
    networks:
      - my_network

  test-db:
    container_name: test-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stats
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - my_network

  dumped-db:
    container_name: dumped-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mensa
    ports:
      - "5432:5432"
    volumes:
      - ./tests/dumps/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - my_network
    profiles:
      - dumpdb

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0@sha256:2f602552550869fb29b6fd5848c5118d3ef3a2e1d5d45802e3ab9088cb2de8e2
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - action.destructive_requires_name=false
      - xpack.monitoring.collection.enabled=false
      - ES_LOG_LEVEL=trace
      - logger.org.elasticsearch.index.search.slowlog=TRACE
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 30
    networks:
      - my_network
    volumes:
      - jaeger_data:/usr/share/elasticsearch/data

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - COLLECTOR_OTLP_ENABLED=true
      - ES_TAGS_AS_FIELDS_ALL=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
    networks:
      - my_network
    depends_on:
      elasticsearch:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network
    command: ["redis-server", "--appendonly", "yes"]

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - test-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    networks:
      - my_network

volumes:
  jaeger_data:
  pgadmin_data:

networks:
  my_network:
