"""
This module is used to import all the models from the database package."""

from .data import QueryRequest, QueryResponse
from .models import (
    Addresses,
    AddressesAudit,
    BaseSQLModel,
    CertsAntecCriminais,
    Emails,
    EmailsAudit,
    Feedback,
    GroupList,
    GroupRequests,
    IAMGroupPermissionsMap,
    IAMGroups,
    IAMPermissions,
    IAMRolePermissionsMap,
    IAMRoles,
    IAMUserGroupsMap,
    IAMUserRolesMap,
    LegalRepresentatives,
    MemberGroups,
    MembershipPayments,
    MembershipPaymentsAudit,
    Phones,
    PhonesAudit,
    Registration,
    RegistrationAudit,
    WhatsappAuthorization,
    WhatsappComms,
    WhatsappMessages,
    WhatsappWorkers,
)
from .pending_registration import PendingRegistration
from .volunteer import (
    VolunteerActivityCategory,
    VolunteerActivityEvaluation,
    VolunteerActivityLog,
    VolunteerCategoryRolePermission,
    VolunteerPointTransaction,
)
from .whatsapp import UpdateInput

# Specify all accessible imports for the package
__all__ = [
    "BaseSQLModel",
    "QueryRequest",
    "QueryResponse",
    "UpdateInput",
    "AddressesAudit",
    "EmailsAudit",
    "GroupRequests",
    "MembershipPaymentsAudit",
    "PhonesAudit",
    "Registration",
    "RegistrationAudit",
    "Addresses",
    "CertsAntecCriminais",
    "Emails",
    "LegalRepresentatives",
    "MemberGroups",
    "MembershipPayments",
    "Phones",
    "WhatsappComms",
    "GroupList",
    "WhatsappMessages",
    "IAMRoles",
    "IAMGroups",
    "IAMPermissions",
    "IAMRolePermissionsMap",
    "IAMGroupPermissionsMap",
    "IAMUserRolesMap",
    "IAMUserGroupsMap",
    "VolunteerActivityCategory",
    "VolunteerActivityLog",
    "VolunteerActivityEvaluation",
    "VolunteerPointTransaction",
    "PendingRegistration",
    "WhatsappAuthorization",
    "Feedback",
    "VolunteerCategoryRolePermission",
    "WhatsappWorkers",
]
