"""drop_wpp_messages_constraints

Revision ID: 035aae50e37d
Revises: 8eccef203631
Create Date: 2025-01-28 10:04:41.541133

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "035aae50e37d"
down_revision: str | None = "8eccef203631"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("whatsapp_messages_group_id_fkey", "whatsapp_messages", type_="foreignkey")
    op.drop_constraint(
        "whatsapp_messages_registration_id_fkey", "whatsapp_messages", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "whatsapp_messages_registration_id_fkey",
        "whatsapp_messages",
        "registration",
        ["registration_id"],
        ["registration_id"],
    )
    op.create_foreign_key(
        "whatsapp_messages_group_id_fkey",
        "whatsapp_messages",
        "group_list",
        ["group_id"],
        ["group_id"],
    )
    # ### end Alembic commands ###
