"""add_whatsapp_authorization_table

Revision ID: 0f29579690ba
Revises: 6450aa894cb9
Create Date: 2025-05-09 10:48:46.217344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f29579690ba'
down_revision: Union[str, None] = '6450aa894cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_authorization',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('is_legal_representative', sa.Boolean(), nullable=False),
    sa.Column('legal_representative_id', sa.Integer(), nullable=True),
    sa.Column('represented_registration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legal_representative_id'], ['legal_representatives.representative_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registration.registration_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['represented_registration_id'], ['registration.registration_id'], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint('auth_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsapp_authorization')
    # ### end Alembic commands ###
