"""add_effectivation_column

Revision ID: 236c0ee11888
Revises: bfdb84a1c6ce
Create Date: 2025-06-27 16:08:44.377846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '236c0ee11888'
down_revision: Union[str, None] = 'bfdb84a1c6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_registration', sa.Column('member_effectivation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_registration', 'member_effectivation_date')
    # ### end Alembic commands ###
