"""change_group_requests

Revision ID: 37efd1521b12
Revises: a928e2f93515
Create Date: 2024-12-17 10:34:39.319945

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37efd1521b12"
down_revision: str | None = "a928e2f93515"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group_requests", "phone_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_requests",
        sa.Column("phone_number", sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
