"""change_group_requests

Revision ID: 37efd1521b12
Revises: a928e2f93515
Create Date: 2024-12-17 10:34:39.319945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '37efd1521b12'
down_revision: Union[str, None] = 'a928e2f93515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_requests', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_requests', sa.Column('phone_number', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
