"""add_whatsapp_message_table

Revision ID: 4cf0d9c18cef
Revises: e97ed03b2941
Create Date: 2025-01-23 14:39:50.602206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4cf0d9c18cef'
down_revision: Union[str, None] = 'e97ed03b2941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('group_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_list.group_id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registration.registration_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_group_id'), 'whatsapp_messages', ['group_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_registration_id'), 'whatsapp_messages', ['registration_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_timestamp'), 'whatsapp_messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_timestamp'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_registration_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_group_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    # ### end Alembic commands ###
