"""drop_communication_date_latlong

Revision ID: 6dda2e6dc27f
Revises: 04447ce1b06b
Create Date: 2025-05-07 09:22:44.958240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dda2e6dc27f'
down_revision: Union[str, None] = '04447ce1b06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'latlong')
    op.drop_column('whatsapp_comms', 'communication_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_comms', sa.Column('communication_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('latlong', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
