"""refactor_authorization_tables

Revision ID: 7dc2acaa5517
Revises: a6c710d95905
Create Date: 2025-07-21 10:51:40.780134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7dc2acaa5517'
down_revision: Union[str, None] = 'a6c710d95905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_workers',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('whatsapp_authorization', sa.Column('worker_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_whatsapp_authorization_phone_number'), 'whatsapp_authorization', ['phone_number'], unique=False)
    op.drop_constraint(op.f('whatsapp_authorization_represented_registration_id_fkey'), 'whatsapp_authorization', type_='foreignkey')
    op.drop_constraint(op.f('whatsapp_authorization_legal_representative_id_fkey'), 'whatsapp_authorization', type_='foreignkey')
    op.drop_constraint(op.f('whatsapp_authorization_registration_id_fkey'), 'whatsapp_authorization', type_='foreignkey')
    op.create_foreign_key(None, 'whatsapp_authorization', 'whatsapp_workers', ['worker_id'], ['id'], ondelete='CASCADE')
    op.drop_column('whatsapp_authorization', 'registration_id')
    op.drop_column('whatsapp_authorization', 'legal_representative_id')
    op.drop_column('whatsapp_authorization', 'represented_registration_id')
    op.drop_column('whatsapp_authorization', 'is_legal_representative')
    op.drop_column('whatsapp_authorization', 'authorized')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_authorization', sa.Column('authorized', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('whatsapp_authorization', sa.Column('is_legal_representative', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('whatsapp_authorization', sa.Column('represented_registration_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('whatsapp_authorization', sa.Column('legal_representative_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('whatsapp_authorization', sa.Column('registration_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'whatsapp_authorization', type_='foreignkey')
    op.create_foreign_key(op.f('whatsapp_authorization_registration_id_fkey'), 'whatsapp_authorization', 'registration', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('whatsapp_authorization_legal_representative_id_fkey'), 'whatsapp_authorization', 'legal_representatives', ['legal_representative_id'], ['representative_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('whatsapp_authorization_represented_registration_id_fkey'), 'whatsapp_authorization', 'registration', ['represented_registration_id'], ['registration_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_whatsapp_authorization_phone_number'), table_name='whatsapp_authorization')
    op.drop_column('whatsapp_authorization', 'worker_id')
    op.drop_table('whatsapp_workers')
    # ### end Alembic commands ###
