"""add_default_no_of_attempts

Revision ID: 7f4a0eca6562
Revises: f664e9ce0180
Create Date: 2024-12-19 15:38:48.865416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f4a0eca6562'
down_revision: Union[str, None] = 'f664e9ce0180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ### commands manually created ###
    op.alter_column(
        table_name="group_requests",
        column_name="no_of_attempts",
        schema="public",
        server_default=sa.text("0")
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ### commands manually created ###
    op.alter_column(
        table_name="group_requests",
        column_name="no_of_attempts",
        schema="public",
        server_default=None
    )
