"""add_worker_phone_constraint

Revision ID: 884c047eea7a
Revises: 7dc2acaa5517
Create Date: 2025-07-23 12:00:19.758941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '884c047eea7a'
down_revision: Union[str, None] = '7dc2acaa5517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('worker_phone_unique_constraint', 'whatsapp_authorization', ['phone_number', 'worker_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('worker_phone_unique_constraint', 'whatsapp_authorization', type_='unique')
    # ### end Alembic commands ###
