"""add_default_entry_date

Revision ID: 8b918650460a
Revises: 035aae50e37d
Create Date: 2025-01-30 11:34:25.963563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b918650460a'
down_revision: Union[str, None] = '035aae50e37d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    # ### commands manually created ###
    op.alter_column(
        table_name="member_groups",
        column_name="created_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="member_groups",
        column_name="updated_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="member_groups",
        column_name="entry_date",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="addresses_audit",
        column_name="created_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="addresses_audit",
        column_name="updated_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="certs_antec_criminais",
        column_name="created_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="certs_antec_criminais",
        column_name="updated_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="emails_audit",
        column_name="created_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="emails_audit",
        column_name="updated_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="group_requests",
        column_name="created_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="group_requests",
        column_name="updated_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="legal_representatives",
        column_name="created_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="legal_representatives",
        column_name="updated_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="membership_payments_audit",
        column_name="created_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="membership_payments_audit",
        column_name="updated_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="phones_audit",
        column_name="created_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="phones_audit",
        column_name="updated_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="registration_audit",
        column_name="created_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="registration_audit",
        column_name="updated_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="whatsapp_comms",
        column_name="created_at",
        schema="public",
        server_default=sa.text("now()")
    )
    op.alter_column(
        table_name="whatsapp_comms",
        column_name="updated_at",
        schema="public",
        server_default=sa.text("now()")
    )
    # ### end of manual Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    # ### commands manually created ###
    op.alter_column(
        table_name="member_groups",
        column_name="created_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="member_groups",
        column_name="updated_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="member_groups",
        column_name="entry_date",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="addresses_audit",
        column_name="created_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="addresses_audit",
        column_name="updated_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="certs_antec_criminais",
        column_name="created_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="certs_antec_criminais",
        column_name="updated_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="emails_audit",
        column_name="created_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="emails_audit",
        column_name="updated_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="group_requests",
        column_name="created_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="group_requests",
        column_name="updated_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="legal_representatives",
        column_name="created_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="legal_representatives",
        column_name="updated_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="membership_payments_audit",
        column_name="created_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="membership_payments_audit",
        column_name="updated_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="phones_audit",
        column_name="created_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="phones_audit",
        column_name="updated_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="registration_audit",
        column_name="created_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="registration_audit",
        column_name="updated_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="whatsapp_comms",
        column_name="created_at",
        schema="public",
        server_default=None
    )
    op.alter_column(
        table_name="whatsapp_comms",
        column_name="updated_at",
        schema="public",
        server_default=None
    )
    # ### end of manual Alembic commands ###
