"""volunteer role

Revision ID: a6c710d95905
Revises: 236c0ee11888
Create Date: 2025-07-02 17:53:16.446481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a6c710d95905'
down_revision: Union[str, None] = '236c0ee11888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_category_role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['volunteer_activity_category.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['iam_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_category_role_permissions')
    # ### end Alembic commands ###
