"""add constraints to whatsapp comms

Revision ID: a928e2f93515
Revises: 34866525c9ec
Create Date: 2024-12-14 13:54:29.818287

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a928e2f93515"
down_revision: str | None = "34866525c9ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "member_groups", "entry_date", existing_type=sa.DATE(), type_=sa.DateTime(), nullable=True
    )
    op.alter_column(
        "membership_payments",
        "payment_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column("registration", "expelled", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("registration", "deceased", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("registration", "transferred", existing_type=sa.BOOLEAN(), nullable=True)
    op.create_unique_constraint(
        "uq_phone_number_reason", "whatsapp_comms", ["phone_number", "reason"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_phone_number_reason", "whatsapp_comms", type_="unique")
    op.alter_column("registration", "transferred", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("registration", "deceased", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("registration", "expelled", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "membership_payments",
        "payment_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "member_groups", "entry_date", existing_type=sa.DateTime(), type_=sa.DATE(), nullable=False
    )
    # ### end Alembic commands ###
