"""update_fkeys_and_constraints_on_IAM

Revision ID: bb9eb342be3d
Revises: 55498956723f
Create Date: 2025-02-04 10:14:02.703634

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb9eb342be3d"
down_revision: str | None = "55498956723f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "iam_group_permissions_map",
        "group_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "iam_group_permissions_map",
        "permission_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_constraint(
        "iam_group_permissions_map_permission_id_fkey",
        "iam_group_permissions_map",
        type_="foreignkey",
    )
    op.drop_constraint(
        "iam_group_permissions_map_group_id_fkey",
        "iam_group_permissions_map",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "iam_group_permissions_map",
        "iam_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "iam_group_permissions_map",
        "iam_permissions",
        ["permission_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "iam_role_permissions_map", "role_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "iam_role_permissions_map",
        "permission_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_constraint(
        "iam_role_permissions_map_permission_id_fkey",
        "iam_role_permissions_map",
        type_="foreignkey",
    )
    op.drop_constraint(
        "iam_role_permissions_map_role_id_fkey",
        "iam_role_permissions_map",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "iam_role_permissions_map",
        "iam_roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "iam_role_permissions_map",
        "iam_permissions",
        ["permission_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "iam_user_groups_map",
        "registration_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column("iam_user_groups_map", "group_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(
        "iam_user_groups_map_registration_id_fkey",
        "iam_user_groups_map",
        type_="foreignkey",
    )
    op.drop_constraint(
        "iam_user_groups_map_group_id_fkey", "iam_user_groups_map", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "iam_user_groups_map",
        "iam_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "iam_user_groups_map",
        "registration",
        ["registration_id"],
        ["registration_id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "iam_user_roles_map",
        "registration_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column("iam_user_roles_map", "role_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("iam_user_roles_map_role_id_fkey", "iam_user_roles_map", type_="foreignkey")
    op.drop_constraint(
        "iam_user_roles_map_registration_id_fkey",
        "iam_user_roles_map",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "iam_user_roles_map",
        "registration",
        ["registration_id"],
        ["registration_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "iam_user_roles_map", "iam_roles", ["role_id"], ["id"], ondelete="CASCADE"
    )
    op.create_unique_constraint(None, "whatsapp_messages", ["message_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "whatsapp_messages", type_="unique")
    op.drop_constraint(None, "iam_user_roles_map", type_="foreignkey")
    op.drop_constraint(None, "iam_user_roles_map", type_="foreignkey")
    op.create_foreign_key(
        "iam_user_roles_map_registration_id_fkey",
        "iam_user_roles_map",
        "registration",
        ["registration_id"],
        ["registration_id"],
    )
    op.create_foreign_key(
        "iam_user_roles_map_role_id_fkey",
        "iam_user_roles_map",
        "iam_roles",
        ["role_id"],
        ["id"],
    )
    op.alter_column("iam_user_roles_map", "role_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "iam_user_roles_map",
        "registration_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(None, "iam_user_groups_map", type_="foreignkey")
    op.drop_constraint(None, "iam_user_groups_map", type_="foreignkey")
    op.create_foreign_key(
        "iam_user_groups_map_group_id_fkey",
        "iam_user_groups_map",
        "iam_groups",
        ["group_id"],
        ["id"],
    )
    op.create_foreign_key(
        "iam_user_groups_map_registration_id_fkey",
        "iam_user_groups_map",
        "registration",
        ["registration_id"],
        ["registration_id"],
    )
    op.alter_column("iam_user_groups_map", "group_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "iam_user_groups_map",
        "registration_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(None, "iam_role_permissions_map", type_="foreignkey")
    op.drop_constraint(None, "iam_role_permissions_map", type_="foreignkey")
    op.create_foreign_key(
        "iam_role_permissions_map_role_id_fkey",
        "iam_role_permissions_map",
        "iam_roles",
        ["role_id"],
        ["id"],
    )
    op.create_foreign_key(
        "iam_role_permissions_map_permission_id_fkey",
        "iam_role_permissions_map",
        "iam_permissions",
        ["permission_id"],
        ["id"],
    )
    op.alter_column(
        "iam_role_permissions_map",
        "permission_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "iam_role_permissions_map",
        "role_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(None, "iam_group_permissions_map", type_="foreignkey")
    op.drop_constraint(None, "iam_group_permissions_map", type_="foreignkey")
    op.create_foreign_key(
        "iam_group_permissions_map_group_id_fkey",
        "iam_group_permissions_map",
        "iam_groups",
        ["group_id"],
        ["id"],
    )
    op.create_foreign_key(
        "iam_group_permissions_map_permission_id_fkey",
        "iam_group_permissions_map",
        "iam_permissions",
        ["permission_id"],
        ["id"],
    )
    op.alter_column(
        "iam_group_permissions_map",
        "permission_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "iam_group_permissions_map",
        "group_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
