"""add_email_sent_column

Revision ID: bfdb84a1c6ce
Revises: 128086567422
Create Date: 2025-06-09 09:41:42.540661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfdb84a1c6ce'
down_revision: Union[str, None] = '128086567422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_registration', sa.Column('email_sent_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_registration', 'email_sent_at')
    # ### end Alembic commands ###
