"""add discord id column

Revision ID: da883f951481
Revises: 8b918650460a
Create Date: 2025-02-01 18:46:15.714248

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da883f951481"
down_revision: str | None = "8b918650460a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registration", sa.Column("discord_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registration", "discord_id")
    # ### end Alembic commands ###
