"""add whatsapp-message-column

Revision ID: e745774137c2
Revises: da883f951481
Create Date: 2025-02-03 20:31:36.916413

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e745774137c2"
down_revision: str | None = "da883f951481"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("whatsapp_messages", sa.Column("content", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("whatsapp_messages", "content")
    # ### end Alembic commands ###
