"""add_beta_tester_column

Revision ID: e97ed03b2941
Revises: 7f4a0eca6562
Create Date: 2024-12-23 12:57:34.150439

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e97ed03b2941"
down_revision: str | None = "7f4a0eca6562"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registration",
        sa.Column("beta_tester", sa.Boolean(), server_default=sa.text("false"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registration", "beta_tester")
    # ### end Alembic commands ###
