name: CI

on:
  push:
    branches:
    - '**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync -p 3.12

      - name: Run tests with coverage
        env:
          API_HOST: ${{ secrets.API_HOST }}
          API_LOG_LEVEL: ${{ secrets.API_LOG_LEVEL }}
          API_PORT: ${{ secrets.API_PORT }}
          API_TITLE: ${{ secrets.API_TITLE }}
          DATA_ROUTE_API_KEY: ${{ secrets.DATA_ROUTE_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM_WHATSAPP_NUMBER: ${{ secrets.TWILIO_FROM_WHATSAPP_NUMBER }}
          WHATSAPP_ROUTE_API_KEY: ${{ secrets.WHATSAPP_ROUTE_API_KEY }}
        run: |
          uv run coverage run -m pytest -sv .
          uv run coverage report

      - name: Check coverage
        run: |
          COVERAGE=$(uv run coverage report | grep TOTAL | awk '{print $4}' | sed 's/%//')
            echo "Coverage is $COVERAGE%"
            if (( $(echo "$COVERAGE < 1" | bc -l) )); then
              echo "Code coverage is below 90%"
              exit 1
            fi

  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          exit-code: 1
          severity: MEDIUM
